default_platform(:android)

platform :android do
  desc "Bump version"
  lane :bump_version do |options|
    version_type = options[:version_type]
    increment_version_code
    increment_version_name(bump_type: version_type)
  end
end
