name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: "Faiz2015#"
          KEY_PASSWORD: "Faiz2015#"
        run: ./gradlew assembleRelease
      - name: List APK files
        run: find . -name "*.apk"
      - name: Rename APK
        run: |
          APK_PATH=$(find . -name "*.apk")
          mv "$APK_PATH" "Parking Locator ${{ env.VERSION }}.apk"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "Parking Locator ${{ env.VERSION }}.apk"