name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk "app/build/outputs/apk/release/Parking Locator ${{ env.VERSION }}.apk"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "app/build/outputs/apk/release/Parking Locator ${{ env.VERSION }}.apk"
