name: Android CI

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      - name: Build Debug
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: "Faiz2015#"
          KEY_PASSWORD: "Faiz2015#"
        run: ./gradlew assembleRelease
      - name: List APK files
        run: find . -name "*.apk"
      - name: Rename APK
        run: |
          APK_PATH=$(find . -name "*.apk")
          mv "$APK_PATH" "Parking Locator ${{ env.VERSION }}.apk"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "Parking Locator ${{ env.VERSION }}.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}