name: Custom Android Build

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > keystore/release.keystore

      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew clean assembleRelease

      - name: List APK files
        run: find . -name "*.apk"

      - name: Rename APK
        run: |
          APK_PATH=$(find . -name "*.apk")
          mv "$APK_PATH" "Parking Locator ${{ github.ref }}.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "Parking Locator ${{ github.ref }}.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
